# -*- coding: utf-8 -*-
"""HackerRank -Solution -Github Repo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HNcUsnZ-d4AA0npNTcZZnaqjqCG-2yUa
"""

from google.colab import drive

# Commented out IPython magic to ensure Python compatibility.
drive.mount('/content/drive')
#Creating a new Folder for Saving the Solution
!mkdir -p /content/drive/MyDrive/HackerrankSolutions
# %cd /content/drive/MyDrive/HackerrankSolutions

#STEP 2: Manually Collect a Few Hackerrank Solutions
data = {
    "Problem Name": ['''Say "Hello, World!" With Python''', ''' Python If-Else'''],
    "Language": ["Python", "Python"],
    "Solution": [
        ''' if __name__ == '__main__':
    print "Hello, World!"
''',
        '''
        #!/bin/python3

import math
import os
import random
import re
import sys



if __name__ == '__main__':
    n = int(input().strip())

c=n%2
if c!=0:
    print("Weird")
elif c==0 and n>=2 and n<=5 :
    print("Not Weird")
elif c==0 and n>=6 and n<=20 :
    print("Weird")
elif c==0 and n>20:
    print("Not Weird")

        '''
    ]
}

import pandas as pd
df = pd.DataFrame(data)
df.to_csv("hackerrank_solutions.csv", index=False)
print(df)

#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

# STEP 5: Install Git in Colab and Configure GitHub

!git config --global user.email "manisha7kumari7777@gmail.com"
!git config --global user.name "manisha7-ma"

#STEP 6: Clone Your Empty Repository into Colab

# Commented out IPython magic to ensure Python compatibility.
repo_url = "https://<PAT Token>@github.com/manisha7-ma/HackerRank-Python-Edition.git"
!git clone {repo_url}
# %cd HackerRank-Python-Edition

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/HackerrankSolutions/hackerrank_solutions.csv')

for index, row in df.iterrows():
    filename = row['Problem Name'].replace(" ", "_") + ".py"
    with open(filename, "w") as f:
        f.write("# " + row['Problem Name'] + "\n")
        f.write("# Language: " + row['Language'] + "\n\n")
        f.write(row['Solution'])

!git add .
!git commit -m "Added Hackerrank Python solutions"
!git push

